### ISSUE TITLE
Issues for 1.0

### ISSUE THREAD

**Issue by pbashyal-nmdp** [nmdp-bioinformatics/gfe-db#89]
Issues for 1.0
- [ ] Update PR #88 and fix conflicts
- [ ] New Makefile target `make vpc` that builds the network (optional)
- [ ] Keep track of IMGT commits to GFE DB 
- [ ] Testing/Validation
- [ ] Merge `incremental_load` branch to `main`

**Comment by chrisammon3000** [comment]
Some considerations for task #2 (New Makefile target make vpc that builds the network (optional)):
* If multiple gfe-db environments are be created in the same account, some environment variables will need to be different to avoid conflicts, so 1) there should be a way to manage this locally 2) we will want safeguards in place to prevent deploying using the wrong environment variables 3) Resource name conflicts will have to be addressed

1. Managing environments locally
One solution I would offer is to use multiple .env:
```
.env.dev
.env.qa
.env.prod
```

Where we append the $STAGE variable to `.env` &rarr; `.env.${STAGE}` in the Makefile so it only includes those variables.

2. Safeguards against deploying to the wrong environment
* Print the environment to the console and ask user to confirm before deploying or updating, the user should confirm that they are deploying with the correct $STAGE value
* Create a change set and ask user for confirmation before updating
* CloudFormation stacks are now tagged with the git branch, so we can detect if a deployment update is being made from a different branch than what the tag is and ask for user confirmation before continuing. (Deploying the wrong branch to the wrong environment will cause problems)

3. Avoiding resource name conflicts
Shouldn't be an issue as long as every named resource has the $STAGE variable in it's name.

**Comment by chrisammon3000** [comment]
Tasks 1 & 2 are ready for review:
- [x] Update PR #88 and fix conflicts
- [x] New Makefile target `make vpc` that builds the network (optional, available with #90)

The points I mentioned above for managing environments locally, safeguard against deploying to the wrong environment, and avoiding resource name conflicts are implemented. 

Task 3 (Keep track of IMGT commits to GFE DB) just needs to be merged with the most recent PRs first. It includes validation of build outputs and load results but does not include testing yet.
